# $schema: https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-action.json
name: "Maven release"
inputs:
  repository:
    description: "Repository in format: Owner/Repository"
    required: true
  directory:
    description: "Directory to checkout to"
    required: false
    default: "temp"
  releaseVersion:
    description: "Release version"
    required: false
  gavs-cache-path:
    description: "Cache path of Shared bulk release GAV file"
    default: "output"
  gavs-cache-key:
    description: "Cache key of Shared bulk release GAV file"
    default: ""
  maven-token:
    description: "Maven token"
    required: true
  maven-gpg-private-key:
    description: "Maven gpg-private-key"
    required: true
  maven-gpg-passphrase:
    description: "Maven gpg-passphrase"
    required: true

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: '${{ inputs.repository }}'
        ref: "main"
        token: '${{ inputs.maven-token }}'
        path: ${{ inputs.directory }}

    - name: Restore GAV cache
      if: ${{ inputs.gavs-cache-key != '' }}
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.gavs-cache-path }}
        key: ${{ inputs.gavs-cache-key }}

    - name: Create files
      if: ${{ inputs.gavs-cache-key == '' }}
      shell: bash
      # language="shell script"
      run: |-
        mkdir -p ${{ inputs.gavs-cache-path }}
        echo "" > ${{ inputs.gavs-cache-path }}/gavs.txt

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      env:
        MAVEN_USER: "x-access-token"
        MAVEN_TOKEN: ${{ inputs.maven-token }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.maven-gpg-passphrase }}
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        server-username: MAVEN_USER
        server-password: MAVEN_TOKEN
        gpg-private-key: ${{ inputs.maven-gpg-private-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE

    - name: Set up Git
      shell: bash
      working-directory: ${{ inputs.directory }}
      # language="shell script"
      run: |-
        git config user.email "actions@github.com"
        git config user.name "actions"
        git remote set-url origin https://x-access-token:${{ inputs.maven-token }}@github.com/${{ inputs.repository }}

    - name: Display git config
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: git config --list

    - name: Read GAVs
      id: read-gavs
      shell: bash
      # language="shell script"
      run: |
        set -x
        gavs=$(tr '\n' ',' < ${{ inputs.gavs-cache-path }}/gavs.txt)
        gavs=${gavs%,}
        echo "gavs=${gavs}" >> "$GITHUB_OUTPUT"

    - name: Update dependencies
      id: update
      shell: bash
      working-directory: ${{ inputs.directory }}
      env:
        gavs: ${{ steps.read-gavs.outputs.gavs }}
      # language="shell script"
      run: |-
        set -x
        IFS=','
        for gav in $gavs; do
          if [ -z "$gav" ]; then
            echo "Dependencies are empty."
            break
          fi
          IFS=":"
          read -r groupID artifactId version <<< "$gav"
          ga="$groupID:$artifactId"
          cmd="mvn -B versions:use-dep-version -Dincludes=$ga -DdepVersion=$version"
          eval "$cmd"
          cmd="mvn -B versions:update-properties -Dincludes=$ga -Dmaven.version.ignore=^\(?!$version\).+\$"
          eval "$cmd"
          IFS=','
        done
        unset IFS
        
        changed=$(git diff --quiet)
        if [ "$changed" -eq 0 ]; then
          git add -u
          git commit -m 'updating dependencies before release'
        fi

    - name: Release
      id: release
      shell: bash
      working-directory: ${{ inputs.directory }}
      env:
        gavs: ${{ steps.read-gavs.outputs.gavs }}
        MAVEN_USER: "x-access-token"
        MAVEN_TOKEN: ${{ inputs.maven-token }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.maven-gpg-passphrase }}
      # language="shell script"
      run: |-
        set -x
        mvn -B release:prepare -Dresume=false -DautoVersionSubmodules=true -DreleaseVersion=${{ inputs.releaseVersion }}
        all_gavs="$gavs"
        gavs=`cat 'release.properties' | grep 'project.rel.' | sed 's/project.rel.//g' | sed 's/\\\\//g' | sed 's/=/:/g' | tr '\n' ','`
        gavs=${gavs%,}
        if [ -z "$all_gavs" ]; then
          all_gavs="$gavs"
        else
          all_gavs="$all_gavs"$','"$gavs"
        fi        
        echo "gavs=${gavs}" >> "$GITHUB_OUTPUT"
        echo "all_gavs=${all_gavs}" >> "$GITHUB_OUTPUT"
        mvn -B release:perform -DlocalCheckout=true -DautoVersionSubmodules=true

    - name: Write released GAVs
      shell: bash
      env:
        gavs: ${{ steps.release.outputs.gavs }}
        all_gavs: ${{ steps.release.outputs.all_gavs }}
      # language="shell script"
      run: |
        set -x
        path="${{ inputs.gavs-cache-path }}/gavs.txt"
        
        echo "$all_gavs" | tr ',' '\n' >> $path
        echo "### Released artifacts:" >> $GITHUB_STEP_SUMMARY
        echo "$gavs" | tr ',' '\n' >> $GITHUB_STEP_SUMMARY

    - name: Save gavs to cache
      uses: actions/cache/save@v4
      with:
        path: output
        key: maven-release-output-${{ github.run_id }}

    - name: Rollback release
      if: ${{ failure() }}
      shell: bash
      working-directory: ${{ inputs.directory }}
      # language="shell script"
      run: mvn -B release:rollback
