name: Build Docker images without publishing in trusted contexts

on:
  workflow_call:
    inputs:
      tags:
        required: false
        type: string
        default: ''
        description: 'Tags'
      config-filename:
        required: false
        type: string
        default: 'docker-dev-config.json'
        description: 'Set name only or short path inside .github folder if required'
      ref:
        required: false
        type: string
        description: 'Git reference to use for the build'
      build-args:
        description: 'Build arguments for the Docker image, in key=value format, one per line.'
        required: false
        type: string
        default: ''

permissions: {}

jobs:
  build:
    name: Build Docker images
    permissions:
      contents: read
    uses: $/.github/workflows/docker-build-core.yaml
    with:
      tags: ${{ inputs.tags }}
      dry-run: true
      config-filename: ${{ inputs.config-filename }}
      ref: ${{ inputs.ref }}
      build-args: ${{ inputs.build-args }}
