# $schema: https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json

name: "Maven bulk release"
run-name: Maven bulk release of [${{ inputs.repositoriesFile }}] by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      repositoriesFile:
        description: |-
          yaml file with indexed repositories to release
        required: false
        type: choice
        options:
          - "core-repositories"
          - "test-repositories"
        default: "core-repositories"
      versionIncrementType:
        description: "Version part to increment"
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch
      skipTest:
        description: "skip tests"
        type: boolean
        default: false
      dryRun:
        description: "dry run"
        type: boolean
        default: false
      maven-envs:
        description: "Envs in format 'env1=val1,env2=val2'. Used for testing"
        type: string

concurrency:
  group: ${{ inputs.repositoriesFile }}
  cancel-in-progress: false

permissions:
  actions: write
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_USER: "x-access-token"
      MAVEN_TOKEN: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.maven-gpg-passphrase }}
    outputs:
      result: ${{ steps.run-maven-bulk-release-cli.outputs.result }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          ref: "main"
          token: '${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}'

      - name: "Print resources information"
        shell: bash
        # language="shell script"
        run: |-
          lscpu
          free -h
          df -h
          uname -a

      - name: "Read repositories"
        id: read-repositories
        shell: bash
        env:
          REPOSITORIES_FILE: ${{ inputs.repositoriesFile }}
        # language="shell script"
        run: |
          set -x
          repositories=$(cat ".github/config/${REPOSITORIES_FILE}.txt")
          echo "repositories=\n${repositories}"
          repositories=$(echo "${repositories}" | tr '\n' ',')
          echo "repositories=${repositories}" >> "$GITHUB_OUTPUT"

      - name: "Cache Maven dependencies"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-maven-

      - name: "Set up java"
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            21
          architecture: 'x64'
          distribution: 'temurin'
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_TOKEN
          gpg-private-key: ${{ inputs.maven-gpg-private-key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: "Run maven-bulk-release-cli"
        id: run-maven-bulk-release-cli
        shell: bash
        env:
          REPOSITORIES: ${{ steps.read-repositories.outputs.repositories }}
          VERSION_INCREMENT_TYPE: ${{ inputs.versionIncrementType }}
          SKIP_TEST: ${{ inputs.skipTest }}
          DRY_RUN: ${{ inputs.dryRun }}
        # language="shell script"
        run: |
          set -x
          jarFile="maven-bulk-release-cli-1.0.0-20250523.060851-63-jar-with-dependencies.jar"          
          url="https://maven.pkg.github.com/Netcracker/qubership-core-infra/org.qubership.cloud/maven-bulk-release-cli/1.0.0-SNAPSHOT/${jarFile}"
          curl -L -o "maven-bulk-release-cli.jar" -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}"
                    
          options=""
          if [ "${SKIP_TEST}" = "true" ]; then
            options="${options} --skipTests"
          fi
          if [ "${DRY_RUN}" = "true" ]; then
            options="${options} --dryRun"
          fi
          
          java -jar maven-bulk-release-cli.jar \
          --baseDir=/tmp \
          --gitURL=https://github.com \
          --gitUsername=actions \
          --gitEmail=actions@github.com \
          --gitPassword=${MAVEN_TOKEN} \
          "--groupsPatterns=org\.qubership\..*" \
          --repositories=${REPOSITORIES} \
          --versionIncrementType=${VERSION_INCREMENT_TYPE} \
          --javaVersionToJavaHomeEnv=\
          17=${JAVA_HOME_17_X64},\
          21=${JAVA_HOME_21_X64} \
          --resultOutputFile=${GITHUB_OUTPUT} \
          --summaryFile=${GITHUB_STEP_SUMMARY} \
          --gavsResultFile=/tmp/gavs.txt \
          --dependencyGraphFile=/tmp/graph.dot \
          ${options}

      - name: "Upload gavs artifact"
        uses: actions/upload-artifact@v4
        with:
          name: gavs.txt
          path: /tmp/gavs.txt

      - name: "Upload graph artifact"
        uses: actions/upload-artifact@v4
        with:
          name: graph.dot
          path: /tmp/graph.dot
