# $schema: https://json.schemastore.org/github-workflow.json

name: Maven release

on:
  workflow_call:
    inputs:
      releaseVersion:
        description: "Release version"
        required: true
        type: string
      dependencies:
        description: |-
          Dependencies to update in format:
          <groupId>:<artifactId>:<version>
          <groupId>:<artifactId>:<version>
        required: false
        type: string
    secrets:
      maven-token:
        description: "Maven token"
        required: true
      maven-gpg-private-key:
        description: "Maven gpg-private-key"
        required: true
      maven-gpg-passphrase:
        description: "Maven gpg-passphrase"
        required: true

jobs:
  release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    env:
      MAVEN_USER: "x-access-token"
      MAVEN_TOKEN: ${{ secrets.maven-token }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.maven-gpg-passphrase }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_TOKEN
          gpg-private-key: ${{ secrets.maven-gpg-private-key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Set up Git
        # language="shell script"
        run: |-
          git config user.email "actions@github.com"
          git config user.name "actions"
          git remote set-url origin https://x-access-token:${{ secrets.MAVEN_TOKEN }}@github.com/${{ github.repository }}

      - name: Display git config
        run: git config --list

      - name: Update dependencies
        id: update
        if: ${{ inputs.dependencies != '' }}
        # language="shell script"
        run: |-
          set -x
          dependencies="${{ inputs.dependencies }}"
          IFS=$'\n'
          for line in $dependencies; do
            IFS=":"
            read -r groupID artifactId version <<< "$line"
            ga="$groupID:$artifactId"
            cmd="mvn -B versions:use-dep-version -Dincludes=$ga -DdepVersion=$version"
            eval "$cmd"
            cmd="mvn -B versions:update-properties -Dincludes=$ga -Dmaven.version.ignore=^\(?!$version\).+\$"
            eval "$cmd"
          done
          git add -u
          git commit -m 'updating dependencies before release'

      - name: Release
        if: ${{ success() }}
        # language="shell script"
        run: |-
          mvn -B release:prepare -Dresume=false -DautoVersionSubmodules=true -DreleaseVersion=${{ inputs.releaseVersion }} release:perform -DlocalCheckout=true

#      - name: Rollback 'Update dependencies'
#        if: ${{ failure() && steps.update.conclusion == 'success' }}
#        run: mvn -B release:rollback

      - name: Rollback release
        if: ${{ failure() }}
        run: mvn -B release:rollback