# $schema: https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json

name: "Maven bulk release"

on:
  workflow_dispatch:
    inputs:
      repositories:
        description: |-
          Repositories to release in json format:
          ["Netcracker/repository-1", "Netcracker/repository-2", "Netcracker/repository-3"]
        required: true
        type: string
        default: |-
          ["Netcracker/qubership-core-release-test-maven-lib-1",
          "Netcracker/qubership-core-release-test-maven-lib-2",
          "Netcracker/qubership-core-release-test-maven-lib-3"]
#      type:
#        description: "Version part to increment"
#        type: choice
#        options:
#          - patch
#          - minor
#          - major
#        default: patch


permissions:
  actions: write
  contents: write
  packages: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      MAVEN_USER: "x-access-token"
      MAVEN_TOKEN: ${{ secrets.maven-token }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.maven-gpg-passphrase }}

    steps:
      - name: Create shared GAVs file
        run: touch gavs.txt

      - name: Upload clean gavs artifact
        uses: actions/upload-artifact@v4
        with:
          name: "gavs-${{ github.run_id }}"
          path: gavs.txt
          overwrite: true

  release:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: ${{ fromJson(inputs.repositories) }}
      max-parallel: 1
    env:
      GH_TOKEN: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository }}'
          ref: "main"

      - name: "Run '${{ matrix.repository }}' repository release"
        uses: "./.github/actions/maven-release"
        with:
          repository: "${{ matrix.repository }}"
          directory: "${{ matrix.repository }}"
          artifact-name: "gavs-${{ github.run_id }}"
          maven-token: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
          maven-gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          maven-gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
