name: Renovate 3rd party BOMs
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        description: "LOG_LEVEL"
        default: info
        options:
          - info
          - debug

  schedule:
    - cron: '35 10 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Renovate
        uses: renovatebot/github-action@v42.0.4
        env:
          RENOVATE_MAVEN_USER: "x-access-token"
          RENOVATE_MAVEN_TOKEN: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
          LOG_LEVEL: ${{ github.event.inputs.log-level || 'info' }}
        with:
          configurationFile: renovate/3rd-party-config.js
          token: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}