name: Renovate core libs repositories
on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: "dry run"
        default: true
      log-level:
        type: choice
        description: "LOG_LEVEL for renovate"
        default: info
        options:
          - info
          - debug

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      MAVEN_USER: "x-access-token"
      MAVEN_TOKEN: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.maven-gpg-passphrase }}
      CLI_VERSION: "1.1.10"
      DRY_RUN: ${{ github.event.inputs.dry-run || 'false' }}
      LOG_LEVEL: ${{ github.event.inputs.log-level || 'info' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: "Cache maven dependencies"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-maven-

      - name: "Set up java"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          architecture: 'x64'
          distribution: 'temurin'
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_TOKEN
          gpg-private-key: ${{ inputs.maven-gpg-private-key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: "Read repositories"
        id: read-repositories
        shell: bash
        # language="shell script"
        run: |
          repositories=$(cat ".github/config/core-libs-repositories.txt")
          echo "repositories:
          ${repositories}"
          repositories=$(echo -n "${repositories}" | tr '\n' ',')
          echo "repositories=${repositories}" >> "${GITHUB_OUTPUT}"

      - name: "Run maven-effective-dependencies-cli"
        id: run-maven-effective-dependencies-cli
        shell: bash
        env:
          REPOSITORIES: ${{ steps.read-repositories.outputs.repositories }}
        # language="shell script"
        run: |
          cliVersion="${CLI_VERSION}"
          name="maven-effective-dependencies-cli"
          url="https://maven.pkg.github.com/Netcracker/qubership-core-bulk-release/org.qubership.cloud/${name}/${cliVersion}/${name}-${cliVersion}-jar-with-dependencies.jar"
          curl -L -v -o "${name}.jar" -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}"
                   
          args="--baseDir=$GITHUB_WORKSPACE"
          args="${args} --type1=spring"
          args="${args} --type2=quarkus"
          args="${args} --type1PomRelativeDir=dependencies/spring-dependencies/pom.xml"
          args="${args} --type2PomRelativeDir=dependencies/quarkus-dependencies/pom.xml"
          args="${args} --gitURL=https://github.com"
          args="${args} --gitUsername=actions"
          args="${args} --gitEmail=actions@github.com"
          args="${args} --gitPassword=${MAVEN_TOKEN}"
          args="${args} --repositories=${REPOSITORIES}"
          args="${args} --resultOutputFile=diff.yaml"
          args="${args} --gavsOutputFile=gavs.txt"
          cmd="java -jar ${name}.jar ${args}"
          echo "running cmd: ${cmd}"
          eval "${cmd}"

      - name: "Upload gavs.txt artifact"
        uses: actions/upload-artifact@v4
        with:
          name: gavs.txt
          path: gavs.txt

      - name: "Upload diff.yaml artifact"
        uses: actions/upload-artifact@v4
        with:
          name: diff.yaml
          path: diff.yaml

      - name: "Run renovate-config-cli"
        id: run-renovate-config-cli
        shell: bash
        env:
          REPOSITORIES: ${{ steps.read-repositories.outputs.repositories }}
        # language="shell script"
        run: |
          cliVersion="${CLI_VERSION}"
          name="renovate-config-cli"
          url="https://maven.pkg.github.com/Netcracker/qubership-core-bulk-release/org.qubership.cloud/${name}/${cliVersion}/${name}-${cliVersion}-jar-with-dependencies.jar"
          curl -L -v -o "${name}.jar" -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}"
          
          repositories=$(echo -n "${REPOSITORIES}" | sed 's|https://github.com/||g' | tr '\n' ',')
          
          hostRules="maven[matchHost=https://repo.maven.apache.org/maven2;username=process.env.RENOVATE_MAVEN_USER;password=process.env.RENOVATE_MAVEN_TOKEN],\
          maven[matchHost=https://maven.pkg.github.com/Netcracker/**;username=process.env.RENOVATE_MAVEN_USER;password=process.env.RENOVATE_MAVEN_TOKEN]"
          
          args="--platform=github"
          args="${args} --repositories=${repositories}"
          args="${args} \"--hostRules=${hostRules}\""
          args="${args} --gavsFile=gavs.txt"
          args="${args} --renovateConfigOutputFile=renovate-config.js"
          if [ "${DRY_RUN}" = "true" ]; then
            args="${args} --dryRun=full"
          fi
          cmd="java -jar ${name}.jar ${args}"
          echo "running cmd: ${cmd}"
          eval "${cmd}"

      - name: "Upload renovate-config.js artifact"
        uses: actions/upload-artifact@v4
        with:
          name: renovate-config.js
          path: renovate-config.js

      - name: Renovate
        uses: renovatebot/github-action@v42.0.4
        env:
          RENOVATE_MAVEN_USER: "x-access-token"
          RENOVATE_MAVEN_TOKEN: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
