name: Renovate core repositories
on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      MAVEN_USER: "x-access-token"
      MAVEN_TOKEN: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.maven-gpg-passphrase }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          path: workflow-repo

      - name: "Cache maven dependencies"
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-maven-

      - name: "Set up java"
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          architecture: 'x64'
          distribution: 'temurin'
          server-id: github
          server-username: MAVEN_USER
          server-password: MAVEN_TOKEN
          gpg-private-key: ${{ inputs.maven-gpg-private-key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: "Run maven-effective-dependencies-cli"
        id: run-maven-effective-dependencies-cli
        shell: bash
        # language="shell script"
        run: |
          cliVersion="1.1.0"
          name="maven-effective-dependencies-cli"
          url="https://maven.pkg.github.com/Netcracker/qubership-core-bulk-release/org.qubership.cloud/${name}/${cliVersion}/${name}-${cliVersion}-jar-with-dependencies.jar"
          curl -L -v -o "${name}.jar" -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}"
          
          #libs=$(cat ".github/config/core-libs-repositories.txt" | tr '\n' ',')
          #services=$(cat ".github/config/core-services-repositories.txt" | tr '\n' ',')
          #repositories="${libs},${services}"
          repositories=$(cat "workflow-repo/.github/config/test-repositories.txt" | tr '\n' ',')
          
          args="--baseDir=workflow-repo"
          args="${args} --type1=spring"
          args="${args} --type2=quarkus"
          args="${args} --type1PomRelativeDir=dependencies/spring-dependencies/pom.xml"
          args="${args} --type2PomRelativeDir=dependencies/quarkus-dependencies/pom.xml"
          args="${args} --gitURL=https://github.com"
          args="${args} --gitUsername=actions"
          args="${args} --gitEmail=actions@github.com"
          args="${args} --gitPassword=${MAVEN_TOKEN}"
          args="${args} --repositories=${repositories}"
          args="${args} --resultOutputFile=workflow-repo/diff.yaml"
          args="${args} --gavsOutputFile=workflow-repo/gavs.txt"
          cmd="java -jar ${name}.jar ${args}"
          echo "running cmd: ${cmd}"
          eval "${cmd}"

      - name: "Upload gavs.txt artifact"
        uses: actions/upload-artifact@v4
        with:
          name: gavs.txt
          path: workflow-repo/gavs.txt

      - name: "Upload diff.yaml artifact"
        uses: actions/upload-artifact@v4
        with:
          name: diff.yaml
          path: workflow-repo/diff.yaml

      - name: "Run renovate-config-cli"
        id: run-renovate-config-cli
        shell: bash
        # language="shell script"
        run: |
          cliVersion="1.1.0"
          name="renovate-config-cli"
          url="https://maven.pkg.github.com/Netcracker/qubership-core-bulk-release/org.qubership.cloud/${name}/${cliVersion}/${name}-${cliVersion}-jar-with-dependencies.jar"
          curl -L -v -o "${name}.jar" -H "Authorization: Bearer ${MAVEN_TOKEN}" "${url}"
          
          gavs=$(cat "workflow-repo/gavs.txt" | tr '\n' ',')
          #libs=$(cat ".github/config/core-libs-repositories.txt" | tr '\n' ',')
          #services=$(cat ".github/config/core-services-repositories.txt" | tr '\n' ',')
          #repositories="${libs},${services}"
          repositories=$(cat "workflow-repo/.github/config/test-repositories.txt" | tr '\n' ',')
          
          args="--platform=github"
          args="${args} --repositories=${repositories}"
          args="${args} --gavs=${gavs}"
          args="${args} --renovateConfigOutputFile=workflow-repo/renovate-config.js"
          args="${args} --dryRun=full"
          cmd="java -jar ${name}.jar ${args}"
          echo "running cmd: ${cmd}"
          eval "${cmd}"

      - name: "Upload renovate-config.js artifact"
        uses: actions/upload-artifact@v4
        with:
          name: renovate-config.js
          path: workflow-repo/renovate-config.js

      - name: Renovate
        uses: renovatebot/github-action@v42.0.4
        with:
          configurationFile: workflow-repo/renovate-config.js
          token: ${{ secrets.MAVEN_RELEASE_DEV_TOKEN }}
